logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        rewriteBatchedStatements: true
        useLocalSessionState: true
        useServerPrepStmts: true
      maximum-pool-size: 5
      pool-name: BeerDB-Pool
    password: beer
    url: jdbc:mariadb://127.0.0.1:3306/beerdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: beer
  flyway:
    enabled: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        format_sql: true
        show_sql: true
