server:
  port: 8081

spring:
  datasource:
    username: beer
    password: beer
    url: jdbc:mariadb://127.0.0.1:3306/beerdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: RestDB-Pool
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false    

  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        ddl-auto: validate
        show_sql: false
        format_sql: false

  flyway:
    enabled: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: info
